name: Publish Demo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: |
          ./install-all.sh
      - name: Install GitHub Pages
        run: |
          npm install -g gh-pages@3.0.0
      - name: Build Website
        run: |
          mkdir dist
          echo "css-in-mf.samples.piral.cloud" > dist/CNAME
          echo "Coming soon!" > dist/index.html
      - name: Deploy Website
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          gh-pages -d "dist" -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
